<a href="https://colab.research.google.com/github/DmitryKutsev/cross-document_coreference/blob/main/classifiers/new_decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [340]:
from sklearn import tree
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [341]:
from IPython.display import SVG, display, HTML

In [342]:
from google.colab import drive
drive.mount('./content', force_remount=False)

Drive already mounted at ./content; to attempt to forcibly remount, call drive.mount("./content", force_remount=True).


In [343]:
!ls
import os
for i in os.listdir('content/'):
  print(i)

content			coref_df_anns60k.csv.3	new_anns60k.csv.3
coref_df_anns60k.csv	new_anns60k.csv		new_df_anns60k.csv
coref_df_anns60k.csv.1	new_anns60k.csv.1	sample_data
coref_df_anns60k.csv.2	new_anns60k.csv.2
.file-revisions-by-id
MyDrive
.shortcut-targets-by-id
.Trash


In [344]:
!wget https://raw.githubusercontent.com/DmitryKutsev/cross-document_coreference/main/data/coref_df_anns60k.csv
!wget https://raw.githubusercontent.com/DmitryKutsev/cross-document_coreference/main/data/new_anns60k.csv

--2021-05-16 12:43:30--  https://raw.githubusercontent.com/DmitryKutsev/cross-document_coreference/main/data/coref_df_anns60k.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1162863 (1.1M) [text/plain]
Saving to: ‘coref_df_anns60k.csv.4’

coref_df_anns60k.cs 100%[===================>]   1.11M  --.-KB/s    in 0.02s   

2021-05-16 12:43:30 (46.3 MB/s) - ‘coref_df_anns60k.csv.4’ saved [1162863/1162863]

--2021-05-16 12:43:30--  https://raw.githubusercontent.com/DmitryKutsev/cross-document_coreference/main/data/new_anns60k.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP reque

In [345]:
import csv
import re
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

In [346]:
with open('coref_df_anns60k.csv') as csvfile:
  reader = csv.reader(csvfile, delimiter='\t')
  with open('new_df_anns60k.csv', 'w') as write_file:
    writer = csv.writer(write_file, delimiter='\t')
    c = 0
    for row in reader:
      new_row = [i if i and not re.match(r'\t+?', i) else '-' for i in row]
      # print(new_row)
      if len(new_row) > 9:
        # print(new_row[:9])
        new_row = new_row[:9]
      writer.writerow(new_row)


In [347]:
files.download('new_df_anns60k.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [348]:
# anns_df = pd.read_csv('coref_df_anns60k.csv', delimiter='\t', error_bad_lines=False, header=None)
anns_df = pd.read_csv('new_df_anns60k.csv', delimiter='\t')

In [349]:
anns_df

TOKEN  TOPIC_NUM  POST_NUM  ...        HEAD  NER  COREFERENCE_CLUSTER
0       обсуждаем          1         0  ...   обсуждаем    0                  0.0
1        препарат          1         0  ...   обсуждаем    0                  0.0
2      рисперидон          1         0  ...    препарат    1                  2.0
3       рисполепт          1         0  ...  рисперидон    1                  3.0
4        сперидан          1         0  ...   рисполепт    1                  4.0
...           ...        ...       ...  ...         ...  ...                  ...
26492           и         22        68  ...     пошлины    0                  0.0
26493  таможенные         22        68  ...     пошлины    0                  0.0
26494     пошлины         22        68  ...        есть    0                  0.0
26495         как         22        68  ...        есть    0                  0.0
26496      светка         22        69  ...      светка    0                  0.0

[26497 rows x 9 columns]

In [350]:
import numpy as np

In [351]:
cor_df = pd.read_csv('content/MyDrive/coref_fasttext60k.csv', delimiter=' ')

In [352]:

np.matrix(cor_df.HEAD_VECT[0]).A[0]

array([-2.08233938e-01,  9.96180058e-01, -2.79894114e-01, -9.09143448e-01,
        3.49961907e-01,  1.22820950e+00, -4.53999013e-01, -4.96644318e-01,
       -5.06227851e-01, -3.50297660e-01, -2.68426925e-01, -3.18647206e-01,
       -4.94759202e-01, -4.05789405e-01, -6.19022734e-02,  5.76916397e-01,
        6.45665407e-01, -6.29692733e-01, -2.28346493e-02,  4.74443585e-01,
        2.75724858e-01,  1.00444555e-01, -2.81267107e-01,  7.38310993e-01,
        1.64172634e-01, -1.40955552e-01, -1.34702528e+00, -2.28699774e-01,
       -2.00072408e-01,  1.53492257e-01,  2.15266779e-01, -3.75066400e-01,
        9.79104459e-01,  1.09640598e-01,  4.11819309e-01, -5.48374474e-01,
        5.74254513e-01,  1.78177617e-02,  2.20505193e-01,  8.06000233e-01,
       -3.45855951e-01, -9.48401261e-03, -1.23907340e+00, -7.95203969e-02,
       -7.97536790e-01, -5.43104485e-02,  4.87657279e-01,  5.39513767e-01,
       -2.17315450e-01, -3.24471802e-01, -3.16938460e-02, -4.50928695e-02,
       -3.87996256e-01,  

In [353]:
cosine_similarity([np.matrix(cor_df.TOKEN_VECT[2]).A[0]], [np.matrix(cor_df.TOKEN_VECT[3]).A[0]])[-1][-1]

0.8436395154681279

# **VECTORS HANDLING**

In [354]:
cor_df.TOKEN_VECT = [np.matrix(i).A[0] for i in cor_df.TOKEN_VECT]

In [355]:
cor_df.HEAD_VECT = [np.matrix(i).A[0] for i in cor_df.HEAD_VECT]

In [356]:
cor_df.SENT_VECT = [np.matrix(i).A[0] for i in cor_df.SENT_VECT]

In [357]:
cor_df.HEAD_CHILDS_VECT = [np.matrix(i).A[0] for i in cor_df.HEAD_CHILDS_VECT]

In [358]:
cor_df['NER'] = anns_df['NER']
cor_df['COREFERENCE_CLUSTER'] = anns_df['COREFERENCE_CLUSTER']
cor_df

TOKEN  ... COREFERENCE_CLUSTER
0       обсуждаем  ...                 0.0
1        препарат  ...                 0.0
2      рисперидон  ...                 2.0
3       рисполепт  ...                 3.0
4        сперидан  ...                 4.0
...           ...  ...                 ...
26492           и  ...                 0.0
26493  таможенные  ...                 0.0
26494     пошлины  ...                 0.0
26495         как  ...                 0.0
26496      светка  ...                 0.0

[26497 rows x 23 columns]

In [359]:
df = cor_df.iloc[:6541,:]

In [106]:
len(df.loc[df['NER'] == 1])

283

In [108]:
len(df.loc[df['NER'] == 3])

54

In [109]:
len(df.loc[df['NER'].isin([1,2,3])])

426

In [107]:
len(df.loc[df['NER'] == 2])

89

In [110]:
df.loc[df['NER'].isin([1,2,3])]

TOKEN  ... COREFERENCE_CLUSTER
2         рисперидон  ...                 2.0
3          рисполепт  ...                 3.0
4           сперидан  ...                 4.0
142       рисполепта  ...               142.0
344       рисполепта  ...               344.0
...              ...  ...                 ...
6502              он  ...               270.0
6517       тиапридом  ...               319.0
6526        препарат  ...               319.0
6535  метоклопрамида  ...               337.0
6539         тиаприд  ...               341.0

[426 rows x 23 columns]

# **SEMANTIC AXIS**

In [360]:
df['TOPIC_NUM'] == 0

0       False
1       False
2       False
3       False
4       False
        ...  
6536    False
6537    False
6538    False
6539    False
6540    False
Name: TOPIC_NUM, Length: 6541, dtype: bool

In [361]:
(df['TOPIC_NUM'] == 0)
axis_df = df.query('POST_NUM == 0 and TOKEN_NUM == 2 and SENT_NUM == 0')
axis_df

TOKEN  ... COREFERENCE_CLUSTER
2      рисперидон  ...                 2.0
576       зелдокс  ...                 2.0
1870    оланзапин  ...                 2.0
5555  галоперидол  ...                 2.0
6200      тиаприд  ...                 3.0

[5 rows x 23 columns]

In [362]:
sum(df.query('POST_NUM == 0 and TOKEN_NUM == 2 and SENT_NUM == 0').TOKEN_VECT)/len(df.query('POST_NUM == 0 and TOKEN_NUM == 2 and SENT_NUM == 0').TOKEN_VECT)

array([ 0.11242506,  1.06504189,  0.60962812, -0.1098321 , -0.25309914,
        0.18837714, -0.29014948, -0.66894132,  0.12588727, -0.36141735,
       -0.05396164, -0.35577641, -0.14144993, -0.15987718, -0.68407827,
       -0.04969584,  0.04704007,  0.06857683,  0.14719775, -0.42784514,
        0.12565804, -0.09923978, -0.46527826,  0.02228641, -0.29075186,
        0.19580094, -0.26369618, -0.26473205, -0.52919418,  0.07394732,
       -0.1234136 , -0.1277977 , -0.02898717,  0.14748353,  0.18349706,
       -0.02373637,  0.25928119, -0.35122524, -0.0759414 ,  0.94526116,
        0.08296286,  0.64028589, -0.28902657,  0.08378753, -0.44904899,
       -0.24238156,  0.36918995, -0.20184582, -0.20304089, -0.099586  ,
        0.13669602,  0.38995985, -0.19354978, -0.37518906,  0.09664967,
        0.01878619, -0.22422224, -0.06534558,  0.09065832, -0.05079969,
       -0.09178696, -0.39066393, -0.03679946, -0.37383265, -0.24993176,
       -0.28516305,  0.65741815, -0.18487955,  0.46176331,  0.12

In [363]:
token_axe = sum(axis_df.TOKEN_VECT)/len(axis_df.TOKEN_VECT)
head_axe = sum(axis_df.HEAD_VECT)/len(axis_df.HEAD_VECT)
head_childs_axe = sum(axis_df.HEAD_CHILDS_VECT)/len(axis_df.HEAD_CHILDS_VECT)
sent_axe = sum(axis_df.SENT_VECT)/len(axis_df.SENT_VECT)

In [365]:
df.TOKEN_VECT[710]

array([nan])

In [366]:
def make_similarity(df, col, axe):
  new_col = []
  for ind, vect in enumerate(df[col]):
    try:
      new_col.append(cosine_similarity([axe], [vect])[-1][-1])
    except ValueError:
      new_col.append(0)
  df[col] = new_col



In [367]:
make_similarity(df, 'TOKEN_VECT', token_axe)
make_similarity(df, 'HEAD_VECT', head_axe)
make_similarity(df, 'HEAD_CHILDS_VECT', head_childs_axe)
make_similarity(df, 'SENT_VECT', sent_axe)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/s

In [370]:
df

TOKEN  TOKEN_VECT  ...  NER  COREFERENCE_CLUSTER
0      обсуждаем    0.424228  ...    0                  0.0
1       препарат    0.403455  ...    0                  0.0
2     рисперидон    0.933164  ...    1                  2.0
3      рисполепт    0.863874  ...    1                  3.0
4       сперидан    0.806514  ...    1                  4.0
...          ...         ...  ...  ...                  ...
6536           и    0.195650  ...    0                  0.0
6537         всё    0.250212  ...    0                  0.0
6538           а    0.267463  ...    0                  0.0
6539     тиаприд    0.889868  ...    1                341.0
6540     убирает    0.504835  ...    0                  0.0

[6541 rows x 23 columns]

In [371]:
df.describe()

TOKEN_VECT    IS_ANSWER  ...          NER  COREFERENCE_CLUSTER
count  6541.000000  6541.000000  ...  6541.000000          6541.000000
mean      0.352978     0.929369  ...     0.095245            66.903532
std       0.148008     0.256228  ...     0.403665           370.716460
min       0.000000     0.000000  ...     0.000000             0.000000
25%       0.249610     1.000000  ...     0.000000             0.000000
50%       0.333842     1.000000  ...     0.000000             0.000000
75%       0.416451     1.000000  ...     0.000000             0.000000
max       0.934259     1.000000  ...     3.000000          3653.000000

[8 rows x 11 columns]

In [375]:
for_factorize = 'ANIMACY	CASE	GENDER	PERSON	POS	DEPENDENCY	HEAD	HEAD_ANIMACY	HEAD_CASE	HEAD_GENDER	HEAD_POS'.split()
for_factorize

['ANIMACY',
 'CASE',
 'GENDER',
 'PERSON',
 'POS',
 'DEPENDENCY',
 'HEAD',
 'HEAD_ANIMACY',
 'HEAD_CASE',
 'HEAD_GENDER',
 'HEAD_POS']

In [385]:

_, lbl = pd.factorize(df.ANIMACY)
print(lbl[0])
_

inan


array([-1,  0,  1, ..., -1,  1, -1])

In [386]:
mapping_dict = {}
for col_name in for_factorize:
  col, lbl = pd.factorize(df[col_name])
  df[col_name] = col
  mapping_dict[col_name] = lbl
mapping_dict  

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


{'ANIMACY': Index(['inan', 'anim'], dtype='object'),
 'CASE': Index(['nomn', 'gent', 'datv', 'accs', 'loct', 'ablt', 'loc2'], dtype='object'),
 'DEPENDENCY': Index(['ROOT', 'obj', 'appos', 'parataxis', 'conj', 'advmod', 'ccomp', 'iobj',
        'csubj', 'case', 'obl', 'det', 'nsubj', 'cc', 'discourse', 'fixed',
        'mark', 'amod', 'advcl', 'xcomp', 'nummod', 'nmod', 'nsubj:pass',
        'nummod:gov', 'cop', 'acl:relcl', 'acl', 'aux', 'flat:foreign', 'punct',
        'obl:agent', 'flat', 'aux:pass', 'orphan', 'expl'],
       dtype='object'),
 'GENDER': Index(['masc', 'femn', 'neut'], dtype='object'),
 'HEAD': Index(['обсуждаем', 'препарат', 'рисперидон', 'рисполепт', 'знаю', 'стоило',
        'меня', 'нет', 'проблем', 'лекарством',
        ...
        'ухудшение', 'увеличением', 'дозы', 'рецидив', 'очередной', 'рацион',
        'продолжает', 'увеличивать', 'катадолоном', 'ответьте'],
       dtype='object', length=1312),
 'HEAD_ANIMACY': Index(['inan', 'anim'], dtype='object'),
 'HE

In [ ]:
# X = cor_df.drop(['COREFERENCE_CLUSTER', 'NER', 'TOKEN'], axis=1)
# X_test = cor_df_test.drop(['COREFERENCE_CLUSTER', 'NER', 'TOKEN'], axis=1)
# labels_dict = {}
# test_labels_dict = {}

# for i in X.columns:
#   X[i], lbl = pd.factorize(X[i])
#   labels_dict[i] = lbl

# for i in X_test.columns:
#   X_test[i], lbl = pd.factorize(X_test[i])
#   test_labels_dict[i] = lbl 

# y = cor_df['COREFERENCE_CLUSTER']
# y, y_label = pd.factorize(y)

# y_test = cor_df_test['COREFERENCE_CLUSTER']
# y_test, y_test_label = pd.factorize(y_test)

In [387]:
train, test = train_test_split(df, test_size=0.2)

In [ ]:
train = train.reset_index()

In [401]:

train = train.iloc[:,:24].drop(['TOKEN', 'level_0', 'index'], axis=1)

In [402]:
test = test.reset_index()

In [406]:
test

index       TOKEN  TOKEN_VECT  ...  HEAD_CHILDS_VECT  NER  COREFERENCE_CLUSTER
0      6016           я    0.299118  ...          0.512747    0                  0.0
1      3761   ulegające    0.263834  ...          0.398415    0                  0.0
2      4538         вес    0.455346  ...          0.434450    0                  0.0
3      3350        пила    0.564324  ...          0.729530    0                  0.0
4      2571          мг    0.611221  ...          0.627152    0                  0.0
...     ...         ...         ...  ...               ...  ...                  ...
1304   4198    млн.евро    0.384900  ...          0.409693    0                  0.0
1305    270      писать    0.285828  ...          0.428397    0                  0.0
1306   3658  повышением    0.335698  ...          0.578581    0                  0.0
1307   4869     теряешь    0.281536  ...          0.314980    0                  0.0
1308   1895         знс    0.419914  ...          0.635647    0                  0.0

[1309 rows x 24 columns]

In [412]:
test = test.iloc[:,:24].drop(['TOKEN', 'index'], axis=1)

In [411]:
test

TOKEN_VECT  IS_ANSWER  ...  NER  COREFERENCE_CLUSTER
0       0.299118          1  ...    0                  0.0
1       0.263834          1  ...    0                  0.0
2       0.455346          1  ...    0                  0.0
3       0.564324          1  ...    0                  0.0
4       0.611221          1  ...    0                  0.0
...          ...        ...  ...  ...                  ...
1304    0.384900          1  ...    0                  0.0
1305    0.285828          0  ...    0                  0.0
1306    0.335698          1  ...    0                  0.0
1307    0.281536          1  ...    0                  0.0
1308    0.419914          1  ...    0                  0.0

[1309 rows x 22 columns]

In [ ]:
X = 

In [ ]:
clf = tree.DecisionTreeClassifier()
clf.fit(X, y)

In [ ]:
clf_ent = tree.DecisionTreeClassifier(criterion='entropy')
clf_ent.fit(X, y)

In [ ]:
from graphviz import Source
from sklearn import tree

In [ ]:
# tree.plot_tree(clf)

In [ ]:
# graph = Source(tree.export_graphviz(clf, out_file=None, 
#                                     feature_names=list(X), class_names=uniques, filled=True))

# display(SVG(graph.pipe(format='svg')))

In [ ]:
clf.predict(X_test)

In [ ]:
y_test

In [ ]:
X_test